name: Mutation tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  mutation:
    name: Mutation tests
    runs-on: ubuntu-latest
    env:
      php-version: '8.1'
      php-extensions: pcov, yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for the `git diff` used below for Infection

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}
          ini-values: zend.assertions=1

      - uses: "ramsey/composer-install@v2"

      - name: Creating var directory
        run: mkdir -p var/cache

      - name: Cache Mutation results
        uses: actions/cache@v3.0.10
        with:
          path: var/cache
          key: ${{ runner.os }}-qa-${{ hashFiles('composer.lock') }}-${{ hashFiles('.github/workflows/mutation.yml') }}

      - name: Running mutation tests
        if: github.ref == 'refs/heads/master'
        run: php vendor/bin/infection --threads=$(nproc)
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}

      - name: Running mutation tests
        if: github.event_name == 'pull_request'
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          php vendor/bin/infection --threads=$(nproc) --git-diff-lines --git-diff-base=origin/$GITHUB_BASE_REF --logger-github --ignore-msi-with-no-mutations --only-covered
